name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9' # or your version

      - name: Print Flutter and Dart versions
        run: |
          flutter --version
          dart --version

      - name: List repository files
        run: ls -R

      - name: Install dependencies (verbose)
        run: flutter pub get -v

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}